apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: l8dd84a2w-python 
  janus-idp.io/tekton: l8dd84a2w-python
  backstage.io/kubernetes-id: l8dd84a2w-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: l8dd84a2w-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml