apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l8dd84a2w-python
  janus-idp.io/tekton: l8dd84a2w-python
  backstage.io/kubernetes-id: l8dd84a2w-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: l8dd84a2w-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
