apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l8dd84a2w-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l8dd84a2w-python 
  name: l8dd84a2w-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: l8dd84a2w-python 
